ALTER TABLE "Lead" ADD COLUMN     "comentarios" TEXT,
ADD COLUMN     "ia" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "norma" TEXT NOT NULL,
ADD COLUMN     "paginas" INTEGER NOT NULL,
ADD COLUMN     "plagio" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "prazo" INTEGER NOT NULL,
ADD COLUMN     "revisao" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "valorEstimado" DOUBLE PRECISION NOT NULL;
